### PR TITLE
Display publication dates for blogs

### LINKED ISSUE #3083: The date on the blog page is incorrect.
A blog post from a few years ago is showing up on search engines as if it were from a few months ago (probably when the redocly update was made).

Image

### PR DESCRIPTION
**Pull request by mDuo13**
- [x] Add a custom template for blog pages which is like the regular one except it has "Publication date: YYYY-MM-DD" at the top.
- [x] Apply the custom template to blog pages
- [x] Change the date field of blogs to be a string to work around a Redocly bug.

Hopefully this will fix #3083.

### CODE REVIEW

File: @theme/templates/blogpost.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+width: 100%;
+`;
+
+function PostInfo(data) {
+    return (
+        <div className="blog-post-info">
+            Publication date: {data.data.date}
+        </div>
+    )
+}
```
Comment (maria-robobug) [inline @theme/templates/blogpost.tsx:18]:
```suggestion
function PostInfo({ data }) {
    return (
        <div className="blog-post-info">
            Publication date: {data.date}
        </div>
    )
}
```

Minor suggestion, either way works.

**Review by maria-robobug — APPROVED** [review]
LGTM

**Comment by tequdev** [comment]
<time> tag may be effective.
