### PR TITLE
Fix localized nav

### LINKED ISSUE #2557: Error on code sample Japanese page
https://xrpl.org/ja/resources/code-samples
スクリーンショット 2024-04-20 14 11 16

### PR DESCRIPTION
**Pull request by mDuo13**
- Bump Redocly to the latest version to get various bug fixes. (Without the update, the other changes don't fix the dropdowns.)
- Fix a bug where using the dropdowns from the Japanese version of the site would take you to a mixed-up half-translated version of the site
- Fix a bug where the Code Samples page showed an error page if you tried to view it in the Japanese version of the site.

### CODE REVIEW

File: @theme/plugins/code-samples.js [hunk 1]
```diff
@@ -43,6 +43,7 @@ export function codeSamples() {
 
         actions.createSharedData('code-samples', { codeSamples: sortedSamples, langs: Array.from(allLands) });
         actions.addRouteSharedData('/resources/code-samples/', 'code-samples', 'code-samples');
+        actions.addRouteSharedData('/ja/resources/code-samples/', 'code-samples', 'code-samples');
```
Comment (mDuo13) [inline @theme/plugins/code-samples.js:46]: Note for the future: if we add more languages to the site, we need to add the shared data to more routes here and in the blog index page, unless/until Redocly updates their plugin API.

**Review by tequdev — APPROVED** [review]
LGTM
